name: ambilykk/copilot-usage-report

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  export-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Copilot usage
        uses: ambilykk/copilot-usage-report@main
        with:        
            GITHUB_TOKEN: ${{ secrets.VUE_APP_GITHUB_TOKEN }}
            org_name: callmegreg-demo-org
            file_path: data/Copilot-Usage-Report.csv
    
      - name: Upload Copilot Usage Report
        uses: actions/upload-artifact@v3
        with:
          name: Copilot Usage Report
          path: data/Copilot-Usage-Report.csv