# Vanilla implementation of https://github.com/marketplace/actions/copilot-usage-action

name: austenstone/copilot-usage

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  display-date-and-time-now:
    runs-on: ubuntu-latest
    steps:
      - name: Display date and time now
        run: |
          DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "Date and Time: $DATE" >> $GITHUB_STEP_SUMMARY
        shell: bash

  export-metrics-full:
    runs-on: ubuntu-latest
    needs: display-date-and-time-now
    steps:
      - name: Enterprise Copilot Usage Metrics Export (Full)
        id: export
        uses: austenstone/copilot-usage@v4
        with:
          github-token: ${{ secrets.VUE_APP_GITHUB_TOKEN }}
          enterprise: ${{ secrets.VUE_APP_GITHUB_ENT }}
          organization: "" # defaults to github.repository_owner if unspecified
      - name: Save Export Result to JSON
        run: echo '${{ steps.export.outputs.result }}' > export-metrics-full.json
      - name: Upload Full Metrics Export Result
        uses: actions/upload-artifact@v4
        with:
          name: copilot-metrics-export-full
          path: export-metrics-full.json

  export-metrics-yesterday:
    runs-on: ubuntu-latest
    needs: display-date-and-time-now
    steps:
      - name: Enterprise Copilot Usage Metrics Export (Yesterday)
        id: export
        uses: austenstone/copilot-usage@v4
        with:
          github-token: ${{ secrets.VUE_APP_GITHUB_TOKEN }}
          enterprise: ${{ secrets.VUE_APP_GITHUB_ENT }}
          organization: "" # defaults to github.repository_owner if unspecified
          days: 1 # this will show yesterday's data according to the UTC calendar date, it doesn't include today's uncompleted metrics data.
      - name: Save Export Result to JSON
        run: echo '${{ steps.export.outputs.result }}' > export-metrics-yesterday.json
      - name: Upload Yesterday Metrics Export Result
        uses: actions/upload-artifact@v4
        with:
          name: copilot-metrics-export-yesterday
          path: export-metrics-yesterday.json

  export-org-metrics:
    runs-on: ubuntu-latest
    needs: display-date-and-time-now
    steps:
      - name: Organization Copilot Usage Metrics Export
        id: export
        uses: austenstone/copilot-usage@v4
        with:
          github-token: ${{ secrets.VUE_APP_GITHUB_TOKEN }}
          organization: dsp-testing
      - name: Save Export Result to JSON
        run: echo '${{ steps.export.outputs.result }}' > export-metrics-org.json
      - name: Upload Organization Metrics Export Result
        uses: actions/upload-artifact@v4
        with:
          name: copilot-metrics-export-org
          path: export-metrics-org.json

  export-team-metrics:
    runs-on: ubuntu-latest
    needs: display-date-and-time-now
    outputs:
      result: ${{ steps.export.outputs.result }}
    steps:
      - name: Team Copilot Usage Metrics Export
        id: export
        uses: austenstone/copilot-usage@v4
        with:
          github-token: ${{ secrets.VUE_APP_GITHUB_TOKEN }}
          enterprise: ${{ secrets.VUE_APP_GITHUB_ENT }}
          organization: callmegreg-demo-org
          team: pleasework
      - name: Save Export Result to JSON
        run: echo '${{ steps.export.outputs.result }}' > export-metrics-team.json
      - name: Upload Team Metrics Export Result
        uses: actions/upload-artifact@v4
        with:
          name: copilot-metrics-export-team
          path: export-metrics-team.json